name = "id1"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true
[[routes]]
pattern = "id1.yasnaya.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.id1.yasnaya.my.id"
custom_domain = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "1a59ab31-3b26-4a9d-9142-0a4d7462c85d"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
